#!/usr/bin/env python3
"""Build the notes section from Markdown.

    python3 build.py

Reads content/notes/*.md and writes, in the repository root:

    notes/index.html            the framed Notes app view
    notes/<slug>/index.html     one full-bleed reading page per note
    notes/feed.xml              RSS 2.0
    sitemap.xml                 every page on the site
    index.html                  the four most recent notes, injected into the
                                home screen widget between build markers

The generated HTML is committed. GitHub Pages serves index.html for a
directory, so real directories give clean URLs with no rewrite rules, no
client-side router, and no server-side anything — every article is a static
document with its own title, description and canonical URL.

Standard library only, deliberately. The site has no package.json and no
dependency tree, and a note that takes six blocks of Markdown does not justify
starting one. The Markdown support below is the subset actually used, not a
CommonMark implementation.
"""

import hashlib
import html
import os
import re
import shutil
import sys
from datetime import datetime, timezone
from email.utils import format_datetime
from urllib.parse import urljoin

ROOT = os.path.dirname(os.path.abspath(__file__))
CONTENT = os.path.join(ROOT, 'content', 'notes')
NOTES_DIR = os.path.join(ROOT, 'notes')

SITE = 'https://iosza.in'
AUTHOR = 'Zain Ahmed'
BYLINE = 'Zain A.'
FEED_TITLE = 'Notes — Zain A.'
FEED_DESC = 'Long-form notes on iOS engineering, architecture and the systems around them.'
OG_IMAGE = SITE + '/assets/og-card.png'

# Stamped into every generated file. Also the marker that lets the build prune
# its own stale output without ever touching a hand-written directory.
STAMP = '<!-- generated by build.py — edit content/notes/*.md instead -->'

WIDGET_START = '<!-- build:notes-widget -->'
WIDGET_END = '<!-- /build:notes-widget -->'
WIDGET_COUNT = 4

WORDS_PER_MINUTE = 220


# ---------------------------------------------------------------------------
# Escaping
#
# Everything that comes out of a Markdown file is text until this module says
# otherwise. Both helpers below are applied to the raw source, never to markup
# the renderer has already produced.
# ---------------------------------------------------------------------------

def esc(text):
    """Escape text for an element body."""
    return html.escape(text, quote=False)


def esc_attr(text):
    """Escape text for a double-quoted attribute value."""
    return html.escape(text, quote=True)


SAFE_SCHEME = re.compile(r'^(?:https?:|mailto:|tel:)', re.I)


def safe_href(url):
    """Allow http(s), mail, tel and same-site relative links; drop the rest.

    A javascript: or data: href in a note would be a script injection with
    extra steps, and no legitimate link here needs either.
    """
    url = url.strip()
    if SAFE_SCHEME.match(url):
        return url
    if url.startswith(('/', './', '../', '#')) or re.match(r'^[\w][\w./-]*$', url):
        return url
    return '#'


# ---------------------------------------------------------------------------
# Asset versioning
#
# styles.css and the scripts keep the same URL forever, and the markup is now
# coupled to them tightly enough that a mismatch renders visibly broken rather
# than merely unstyled: a cached stylesheet that predates .note-link lays the
# widget's title and date out inline and lets the preview wrap, which inflates
# the card until it fills the screen. Appending a content hash means a changed
# stylesheet is a changed URL, so that pairing cannot happen.
# ---------------------------------------------------------------------------

def asset(name):
    """Return name with a short content hash appended, for cache busting."""
    path = os.path.join(ROOT, name)
    digest = hashlib.sha1(open(path, 'rb').read()).hexdigest()[:8]
    return '%s?v=%s' % (name, digest)


ASSET_REF = re.compile(r'(href|src)="((?:\.\./)*)(styles\.css|script\.js|clock\.js|reader\.js)(?:\?v=[0-9a-f]+)?"')


def version_assets(markup):
    """Rewrite every local asset reference to carry the current hash."""
    def sub(m):
        attr, prefix, name = m.group(1), m.group(2), m.group(3)
        return '%s="%s%s"' % (attr, prefix, asset(name))
    return ASSET_REF.sub(sub, markup)


# ---------------------------------------------------------------------------
# Markdown — inline
# ---------------------------------------------------------------------------

INLINE = re.compile(
    r'(?P<ticks>`+)(?P<code>.+?)(?P=ticks)'
    r'|!\[(?P<alt>[^\]]*)\]\((?P<src>[^)\s]+)\)'
    r'|\[(?P<text>[^\]]+)\]\((?P<href>[^)\s]+)\)'
    r'|\*\*(?P<strong>\S(?:.*?\S)?)\*\*'
    r'|(?<![\w*])\*(?P<em>[^*\n]+)\*(?![\w*])'
    r'|(?<![\w_])_(?P<em2>[^_\n]+)_(?![\w_])',
    re.S,
)


def inline(text):
    """Render bold, italic, inline code, links and images."""
    out = []
    pos = 0
    for m in INLINE.finditer(text):
        out.append(esc(text[pos:m.start()]))
        if m.group('code') is not None:
            out.append('<code>%s</code>' % esc(m.group('code')))
        elif m.group('src') is not None:
            out.append('<img src="%s" alt="%s" loading="lazy" decoding="async">'
                       % (esc_attr(safe_href(m.group('src'))), esc_attr(m.group('alt'))))
        elif m.group('href') is not None:
            href = safe_href(m.group('href'))
            ext = href.startswith(('http://', 'https://')) and not href.startswith(SITE)
            rel = ' target="_blank" rel="noopener noreferrer"' if ext else ''
            out.append('<a href="%s"%s>%s</a>' % (esc_attr(href), rel, inline(m.group('text'))))
        elif m.group('strong') is not None:
            out.append('<strong>%s</strong>' % inline(m.group('strong')))
        else:
            out.append('<em>%s</em>' % inline(m.group('em') or m.group('em2')))
        pos = m.end()
    out.append(esc(text[pos:]))
    return ''.join(out)


def plain(text):
    """Strip inline markup down to readable text, for previews and metadata."""
    text = re.sub(r'`+([^`]+)`+', r'\1', text)
    text = re.sub(r'!\[[^\]]*\]\([^)]*\)', '', text)
    text = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', text)
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text, flags=re.S)
    text = re.sub(r'(?<![\w*])\*([^*\n]+)\*(?![\w*])', r'\1', text)
    text = re.sub(r'(?<![\w_])_([^_\n]+)_(?![\w_])', r'\1', text)
    return text


# ---------------------------------------------------------------------------
# Markdown — blocks
# ---------------------------------------------------------------------------

FENCE = re.compile(r'^(?P<fence>```+)\s*(?P<lang>[\w+-]*)\s*$')
HEADING = re.compile(r'^(?P<hashes>#{1,4})\s+(?P<text>.+?)\s*#*$')
BULLET = re.compile(r'^[-*]\s+(?P<text>.+)$')
ORDERED = re.compile(r'^\d+[.)]\s+(?P<text>.+)$')
RULE = re.compile(r'^(?:-{3,}|\*{3,}|_{3,})$')


def slugify(text):
    text = re.sub(r'[^\w\s-]', '', plain(text).lower()).strip()
    return re.sub(r'[\s_-]+', '-', text) or 'section'


def render_markdown(source):
    """Render the Markdown subset the notes use.

    Headings, paragraphs, bold, italic, inline code, links, images, ordered and
    unordered lists, fenced code blocks, blockquotes and horizontal rules.
    Anything else is treated as paragraph text, which is the failure mode you
    want: unsupported syntax shows up as literal characters on the page rather
    than as silently dropped content.
    """
    lines = source.replace('\r\n', '\n').split('\n')
    out = []
    seen_ids = {}
    i = 0
    n = len(lines)

    def heading_id(text):
        base = slugify(text)
        seen_ids[base] = seen_ids.get(base, 0) + 1
        return base if seen_ids[base] == 1 else '%s-%d' % (base, seen_ids[base])

    while i < n:
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        fence = FENCE.match(stripped)
        if fence:
            marker = fence.group('fence')
            lang = fence.group('lang')
            i += 1
            body = []
            while i < n and lines[i].strip() != marker:
                body.append(lines[i])
                i += 1
            i += 1  # closing fence, or end of file
            cls = ' class="lang-%s"' % esc_attr(lang) if lang else ''
            label = ('<span class="code-lang" aria-hidden="true">%s</span>' % esc(lang)) if lang else ''
            out.append('<div class="code-block">%s<pre%s><code>%s</code></pre></div>'
                       % (label, cls, esc('\n'.join(body))))
            continue

        if RULE.match(stripped):
            out.append('<hr>')
            i += 1
            continue

        head = HEADING.match(stripped)
        if head:
            # The page supplies the h1, so body headings start at h2 — a second
            # h1 in the article would flatten the document outline. Authors
            # writing under front matter reach for "##" as their top section,
            # so "#" and "##" both land on h2 rather than "##" dropping to h3
            # and leaving the largest heading style unreachable.
            level = min(max(len(head.group('hashes')), 2), 4)
            text = head.group('text')
            out.append('<h%d id="%s">%s</h%d>'
                       % (level, esc_attr(heading_id(text)), inline(text), level))
            i += 1
            continue

        if stripped.startswith('>'):
            body = []
            while i < n and lines[i].strip().startswith('>'):
                body.append(re.sub(r'^\s*>\s?', '', lines[i]))
                i += 1
            out.append('<blockquote>%s</blockquote>' % render_markdown('\n'.join(body)))
            continue

        if BULLET.match(stripped) or ORDERED.match(stripped):
            ordered = ORDERED.match(stripped) is not None
            pattern = ORDERED if ordered else BULLET
            items = []
            while i < n:
                m = pattern.match(lines[i].strip())
                if m:
                    items.append([m.group('text')])
                    i += 1
                elif items and lines[i].strip() and not lines[i].strip().startswith(('#', '>', '```')) \
                        and lines[i][:1] in ' \t':
                    items[-1].append(lines[i].strip())  # continuation line
                    i += 1
                else:
                    break
            tag = 'ol' if ordered else 'ul'
            rendered = ''.join('<li>%s</li>' % inline(' '.join(parts)) for parts in items)
            out.append('<%s class="prose-list">%s</%s>' % (tag, rendered, tag))
            continue

        body = []
        while i < n and lines[i].strip() and not FENCE.match(lines[i].strip()) \
                and not HEADING.match(lines[i].strip()) and not lines[i].strip().startswith('>') \
                and not RULE.match(lines[i].strip()) \
                and not BULLET.match(lines[i].strip()) and not ORDERED.match(lines[i].strip()):
            body.append(lines[i].strip())
            i += 1
        out.append('<p>%s</p>' % inline(' '.join(body)))

    return '\n'.join(out)


# ---------------------------------------------------------------------------
# Front matter
# ---------------------------------------------------------------------------

REQUIRED = ('title', 'date', 'slug', 'description')


def parse_note(path):
    raw = open(path, encoding='utf-8').read().replace('\r\n', '\n')
    if not raw.startswith('---\n'):
        raise SystemExit('%s: missing front matter' % os.path.basename(path))
    end = raw.find('\n---', 3)
    if end == -1:
        raise SystemExit('%s: unterminated front matter' % os.path.basename(path))

    meta = {}
    for line in raw[4:end].split('\n'):
        if not line.strip():
            continue
        if ':' not in line:
            raise SystemExit('%s: front matter line without a colon: %r' % (os.path.basename(path), line))
        key, value = line.split(':', 1)
        meta[key.strip().lower()] = value.strip().strip('"\'')

    missing = [k for k in REQUIRED if not meta.get(k)]
    if missing:
        raise SystemExit('%s: front matter missing %s' % (os.path.basename(path), ', '.join(missing)))

    try:
        date = datetime.strptime(meta['date'], '%Y-%m-%d').replace(tzinfo=timezone.utc)
    except ValueError:
        raise SystemExit('%s: date must be YYYY-MM-DD, got %r' % (os.path.basename(path), meta['date']))

    slug = meta['slug']
    if not re.match(r'^[a-z0-9][a-z0-9-]*$', slug):
        raise SystemExit('%s: slug must be lowercase letters, digits and dashes' % os.path.basename(path))

    body = raw[end + 4:].lstrip('\n')
    words = len(plain(body).split())

    return {
        'path': path,
        'title': meta['title'],
        'date': date,
        'slug': slug,
        'description': meta['description'],
        'body': body,
        'html': render_markdown(body),
        'minutes': max(1, round(words / WORDS_PER_MINUTE)),
        'url': '%s/notes/%s/' % (SITE, slug),
    }


def load_notes():
    if not os.path.isdir(CONTENT):
        raise SystemExit('no content directory at %s' % CONTENT)
    paths = sorted(p for p in os.listdir(CONTENT) if p.endswith('.md'))
    notes = [parse_note(os.path.join(CONTENT, p)) for p in paths]

    seen = {}
    for note in notes:
        if note['slug'] in seen:
            raise SystemExit('duplicate slug %r in %s and %s'
                             % (note['slug'], os.path.basename(seen[note['slug']]['path']),
                                os.path.basename(note['path'])))
        seen[note['slug']] = note

    notes.sort(key=lambda n: (n['date'], n['slug']), reverse=True)
    return notes


# ---------------------------------------------------------------------------
# Dates
# ---------------------------------------------------------------------------

def long_date(d):
    return '%s %d, %d' % (d.strftime('%B'), d.day, d.year)


def short_date(d):
    """The widget's format, unchanged: month/day, no leading zeros, no year."""
    return '%d/%d' % (d.month, d.day)


def list_date(d):
    return '%d/%d/%02d' % (d.month, d.day, d.year % 100)


# ---------------------------------------------------------------------------
# Shared head
# ---------------------------------------------------------------------------

def head(*, title, description, canonical, up, og_type='website', extra=''):
    """`up` is the relative path back to the repository root, so every page
    works from a file:// open as well as from a server."""
    return f'''  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
{STAMP}

  <title>{esc(title)}</title>
  <meta name="description" content="{esc_attr(description)}" />
  <link rel="canonical" href="{esc_attr(canonical)}" />
  <meta name="theme-color" content="#0a0a0c" />
  <meta name="color-scheme" content="dark" />

  <meta property="og:type" content="{og_type}" />
  <meta property="og:url" content="{esc_attr(canonical)}" />
  <meta property="og:title" content="{esc_attr(title)}" />
  <meta property="og:description" content="{esc_attr(description)}" />
  <meta property="og:image" content="{OG_IMAGE}" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:alt" content="Zain A., iOS Engineer" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="{esc_attr(title)}" />
  <meta name="twitter:description" content="{esc_attr(description)}" />
  <meta name="twitter:image" content="{OG_IMAGE}" />
{extra}
  <link rel="icon" href="{up}assets/favicon.svg" type="image/svg+xml" />
  <link rel="apple-touch-icon" href="{up}assets/apple-touch-icon.png" />
  <link rel="alternate" type="application/rss+xml" title="{FEED_TITLE}" href="{up}notes/feed.xml" />

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{up}styles.css">
'''


STATUSBAR = '''        <div class="statusbar" aria-hidden="true">
          <span class="clock" id="time">9:41</span>
          <span class="status-right">
            <span class="signal"><i></i><i></i><i></i><i></i></span>
            <span class="carrier">LTE</span>
            <span class="battery"></span>
          </span>
        </div>'''


# ---------------------------------------------------------------------------
# notes/index.html — the app view, inside the frame
# ---------------------------------------------------------------------------

def render_index(notes):
    rows = []
    for note in notes:
        rows.append(f'''            <li class="note-row">
              <a class="note-row-link" href="{esc_attr(note['slug'])}/">
                <span class="note-row-title">{esc(note['title'])}</span>
                <span class="note-row-meta"><time datetime="{note['date'].strftime('%Y-%m-%d')}">{list_date(note['date'])}</time> &#8226; {esc(note['description'])}</span>
              </a>
            </li>''')

    count = '%d note%s' % (len(notes), '' if len(notes) == 1 else 's')
    ld = '''  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "Blog",
    "name": "Notes — Zain A.",
    "url": "%s/notes/",
    "author": { "@type": "Person", "name": "%s", "url": "%s/" }
  }
  </script>''' % (SITE, AUTHOR, SITE)

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
{head(title='Notes — Zain A.', description=FEED_DESC, canonical=SITE + '/notes/', up='../')}
{ld}
</head>
<body>
  <div class="stage">
    <div class="phone-frame">
      <div class="dynamic-island" aria-hidden="true">
        <span class="island-camera"></span>
      </div>

      <main class="screen screen-app">
{STATUSBAR}

        <section class="notes-app" aria-labelledby="notes-app-title">
          <header class="notes-app-bar">
            <a class="notes-app-back" href="../">
              <span class="notes-app-chevron" aria-hidden="true"></span>
              <span>Home</span>
            </a>
            <h1 class="notes-app-title" id="notes-app-title">
              <span class="notes-glyph" aria-hidden="true"></span>
              Notes
            </h1>
          </header>

          <ul class="notes-app-list">
{chr(10).join(rows)}
          </ul>

          <p class="notes-app-count">{count}</p>
        </section>
      </main>
    </div>
  </div>

  <script src="../clock.js"></script>
</body>
</html>
'''


# ---------------------------------------------------------------------------
# notes/<slug>/index.html — the reading page, no frame
# ---------------------------------------------------------------------------

def render_article(note, newer, older):
    iso = note['date'].strftime('%Y-%m-%d')

    ld = '''  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    "headline": %s,
    "description": %s,
    "datePublished": "%s",
    "dateModified": "%s",
    "mainEntityOfPage": { "@type": "WebPage", "@id": "%s" },
    "url": "%s",
    "image": "%s",
    "author": { "@type": "Person", "name": "%s", "url": "%s/" },
    "publisher": { "@type": "Person", "name": "%s", "url": "%s/" }
  }
  </script>''' % (json_string(note['title']), json_string(note['description']), iso, iso,
                  note['url'], note['url'], OG_IMAGE, AUTHOR, SITE, AUTHOR, SITE)

    extra = ('  <meta property="article:published_time" content="%s" />\n'
             '  <meta property="article:author" content="%s" />\n' % (iso, esc_attr(AUTHOR)))

    nav = []
    if newer:
        nav.append(f'''        <a class="reader-adjacent" href="../{esc_attr(newer['slug'])}/">
          <span class="reader-adjacent-label">Newer</span>
          <span class="reader-adjacent-title">{esc(newer['title'])}</span>
        </a>''')
    if older:
        nav.append(f'''        <a class="reader-adjacent reader-adjacent-older" href="../{esc_attr(older['slug'])}/">
          <span class="reader-adjacent-label">Older</span>
          <span class="reader-adjacent-title">{esc(older['title'])}</span>
        </a>''')
    nav_html = ('''      <nav class="reader-adjacents" aria-label="More notes">
%s
      </nav>
''' % chr(10).join(nav)) if nav else ''

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
{head(title='%s — Zain A.' % note['title'], description=note['description'],
      canonical=note['url'], up='../../', og_type='article', extra=extra)}
{ld}
</head>
<body class="reader">
  <div class="reader-wall" aria-hidden="true"></div>

  <div class="reader-bar">
    <div class="reader-bar-col">
      <a class="reader-bar-back" href="../">
        <span class="notes-app-chevron" aria-hidden="true"></span>
        <span>Notes</span>
      </a>
      <span class="reader-bar-title" aria-hidden="true">{esc(note['title'])}</span>
    </div>
  </div>

  <header class="reader-hero">
    <div class="reader-col">
      <h1 class="reader-title">{esc(note['title'])}</h1>
      <p class="reader-standfirst">{esc(note['description'])}</p>
      <p class="reader-meta">
        <span class="reader-byline">{esc(BYLINE)}</span>
        <time datetime="{iso}">{long_date(note['date'])}</time>
        <span>{note['minutes']} min read</span>
      </p>
    </div>
  </header>

  <main class="reader-main" id="content">
    <article class="reader-col prose">
{indent(note['html'], 6)}
    </article>
  </main>

  <footer class="reader-foot">
    <div class="reader-col">
{nav_html}      <p class="reader-home">
        <a href="../../">
          <span class="reader-home-glyph" aria-hidden="true"></span>
          <span>Back to the home screen</span>
        </a>
      </p>
    </div>
  </footer>

  <script src="../../reader.js" defer></script>
</body>
</html>
'''


def indent(block, spaces):
    """Indent generated markup, leaving <pre> contents alone.

    Whitespace inside <pre> is content. Indenting it uniformly walked every
    line of every code sample to the right by six columns, which turned a Swift
    snippet into a staircase — visible in a render, invisible in the source.
    """
    pad = ' ' * spaces
    out = []
    depth = 0
    for line in block.split('\n'):
        out.append(pad + line if line and depth == 0 else line)
        depth += line.count('<pre') - line.count('</pre>')
    return '\n'.join(out)


def json_string(value):
    """A JSON string literal, for the ld+json blocks."""
    import json
    return json.dumps(value, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Feed and sitemap
# ---------------------------------------------------------------------------

RELATIVE_ATTR = re.compile(r'((?:href|src)=")(?!https?:|mailto:|tel:|#)([^"]*)"')


def absolutise(markup, base):
    """Rewrite relative hrefs against the article's own URL.

    A feed item is read somewhere else entirely, where ../another-note/ points
    at nothing. On the page itself the relative form is what keeps the site
    portable, so the rewrite happens here rather than in the renderer.
    """
    return RELATIVE_ATTR.sub(lambda m: '%s%s"' % (m.group(1), urljoin(base, m.group(2))), markup)


def render_feed(notes):
    # The newest note's date, not the wall clock. The output is committed, so a
    # build that changes nothing should produce no diff — otherwise every run
    # dirties the tree and the real change gets lost in the noise.
    built = notes[0]['date']
    items = []
    for note in notes:
        body = absolutise(note['html'], note['url']).replace(']]>', ']]&gt;')
        items.append(f'''    <item>
      <title>{esc(note['title'])}</title>
      <link>{note['url']}</link>
      <guid isPermaLink="true">{note['url']}</guid>
      <pubDate>{format_datetime(note['date'])}</pubDate>
      <description>{esc(note['description'])}</description>
      <content:encoded><![CDATA[{body}]]></content:encoded>
    </item>''')

    return f'''<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>{esc(FEED_TITLE)}</title>
    <link>{SITE}/notes/</link>
    <description>{esc(FEED_DESC)}</description>
    <language>en</language>
    <lastBuildDate>{format_datetime(built)}</lastBuildDate>
    <atom:link href="{SITE}/notes/feed.xml" rel="self" type="application/rss+xml" />
{chr(10).join(items)}
  </channel>
</rss>
'''


def render_sitemap(notes):
    newest = notes[0]['date'] if notes else datetime.now(timezone.utc)
    urls = [(SITE + '/', newest, '1.0'), (SITE + '/notes/', newest, '0.8')]
    urls += [(n['url'], n['date'], '0.7') for n in notes]
    body = '\n'.join(
        '  <url>\n'
        '    <loc>%s</loc>\n'
        '    <lastmod>%s</lastmod>\n'
        '    <priority>%s</priority>\n'
        '  </url>' % (loc, when.strftime('%Y-%m-%d'), priority)
        for loc, when, priority in urls
    )
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            '%s\n</urlset>\n' % body)


# ---------------------------------------------------------------------------
# Home screen widget
#
# The widget names four specific notes, so it has to stay in step with what is
# actually published. Injecting it here means adding a note is one file and one
# command, rather than one file and a hand edit somebody will forget.
# ---------------------------------------------------------------------------

def render_widget_rows(notes):
    rows = []
    for note in notes[:WIDGET_COUNT]:
        rows.append(f'''              <li class="note-item">
                <a class="note-link" href="notes/{esc_attr(note['slug'])}/">
                  <span class="note-title">{esc(note['title'])}</span>
                  <span class="note-meta">{short_date(note['date'])} &#8226; {esc(note['description'])}</span>
                </a>
              </li>''')
    return '\n'.join(rows)


def inject_widget(notes):
    path = os.path.join(ROOT, 'index.html')
    source = version_assets(open(path, encoding='utf-8').read())
    start = source.find(WIDGET_START)
    end = source.find(WIDGET_END)
    if start == -1 or end == -1:
        raise SystemExit('index.html is missing the %s / %s markers' % (WIDGET_START, WIDGET_END))

    updated = (source[:start + len(WIDGET_START)]
               + '\n' + render_widget_rows(notes) + '\n'
               + ' ' * 14 + source[end:])
    return write(path, updated)


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

written = []


def write(path, text):
    # Single hook: every HTML file the build emits leaves with current asset
    # hashes, whether it was generated here or hand-written and injected into.
    if path.endswith('.html'):
        text = version_assets(text)
    existing = None
    if os.path.exists(path):
        existing = open(path, encoding='utf-8').read()
    if existing == text:
        return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)
    written.append(os.path.relpath(path, ROOT))
    return True


def prune(slugs):
    """Remove article directories for slugs that no longer exist.

    Only directories whose index.html carries this build's stamp are touched,
    so a hand-written page dropped into notes/ is never deleted by a rename.
    """
    if not os.path.isdir(NOTES_DIR):
        return
    for name in sorted(os.listdir(NOTES_DIR)):
        target = os.path.join(NOTES_DIR, name)
        if not os.path.isdir(target) or name in slugs:
            continue
        index = os.path.join(target, 'index.html')
        if os.path.isfile(index) and STAMP in open(index, encoding='utf-8').read():
            shutil.rmtree(target)
            written.append('removed ' + os.path.relpath(target, ROOT))


def main():
    notes = load_notes()
    if not notes:
        raise SystemExit('no notes found in %s' % CONTENT)

    for i, note in enumerate(notes):
        newer = notes[i - 1] if i > 0 else None
        older = notes[i + 1] if i + 1 < len(notes) else None
        write(os.path.join(NOTES_DIR, note['slug'], 'index.html'), render_article(note, newer, older))

    prune({n['slug'] for n in notes})
    write(os.path.join(NOTES_DIR, 'index.html'), render_index(notes))
    write(os.path.join(NOTES_DIR, 'feed.xml'), render_feed(notes))
    write(os.path.join(ROOT, 'sitemap.xml'), render_sitemap(notes))
    inject_widget(notes)

    print('%d note%s' % (len(notes), '' if len(notes) == 1 else 's'))
    for path in written:
        print('  ' + path)
    if not written:
        print('  everything already up to date')
    return 0


if __name__ == '__main__':
    sys.exit(main())
